name: POPMART Stock Checker

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  check-stock:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: docker build -t popmart-stock-checker .
      
    - name: Run stock checker
      run: |
        docker run --rm \
          -e SENDER_EMAIL="${{ secrets.SENDER_EMAIL }}" \
          -e SENDER_PASSWORD="${{ secrets.SENDER_PASSWORD }}" \
          -e RECEIVER_EMAIL="${{ secrets.RECEIVER_EMAIL }}" \
          -e SMTP_SERVER="${{ secrets.SMTP_SERVER }}" \
          -e SMTP_PORT="${{ secrets.SMTP_PORT }}" \
          -e URL="${{ vars.STOCK_CHECK_URL || 'https://www.popmart.com/jp/products/3884' }}" \
          popmart-stock-checker